version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - checkout
      - run: 'apt update && apt upgrade -y && apt install -y sudo'
      - run: 'apt install -y gcc g++ git cmake make wget pkg-config libreadline-dev'
      - run: 'wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz -O googletest.tar.gz'
      - run: 'tar -xf googletest.tar.gz'
      - run: 'cd googletest-release-1.10.0/ && cmake . && make && make install && ldconfig'
      - run: 'cmake -H. -Bbuild'
      - run: 'cmake --build build'
      - run: 'build/examples/simple'
      - run: 'build/examples/version'
      - run: 'build/tests/calculator_tests'
      - run: 'printf "\n1+1\n6676767\ncos(pi)" > input && build/cmd/calc/calc < input && rm input'