version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - checkout
      - run: 'apt update && apt upgrade -y && apt install -y sudo'
      - run: 'apt install -y gcc g++ git cmake make wget pkg-config libreadline-dev mingw-w64 zip'
      - run: 'scripts/get_cpp_linenoise_and_apply_patch.sh'
      - run: 'scripts/install_gtest.sh'
      - run: 'scripts/native_build.sh'
      - run: 'scripts/win32_build.sh'
      - run: 'linux_build_debug/tests/*tests'
      - run: 'linux_build_debug/examples/version'
      - run: 'linux_build_debug/examples/simple'
      - run: 'linux_build_debug/cmd/calc/calc "1+1" "e*cos(pi)" "abs(-1)"'
      - run: 'printf "\n1+1\n6676767\ncos(pi)" > input && linux_build_debug/cmd/calc/calc < input && rm input'
      - store_artifacts:
          path: linux_build.zip
      - store_artifacts:
          path: win32_build.zip
      - store_artifacts:
          path: win32_release.zip
      - store_artifacts:
          path: linux_release.zip