version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:18.04"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 'apt update && apt upgrade -y && apt install -y sudo'
      - run: 'apt install -y gcc g++ git cmake make wget pkg-config libreadline-dev mingw-w64'
      - run: 'scripts/install_gtest.sh'
      - run: 'cc -v'
      - run: 'c++ -v'
      - run: 'echo "core_num=$(nproc 2>/dev/null ||sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN
      2>/dev/null)"'
      - run: 'scripts/native_build.sh'
      - run: '$(uname)_build/tests/*tests'
      - run: '$(uname)_build/examples/version'
      - run: '$(uname)_build/examples/simple'
      - run: '$(uname)_build/cmd/calc/calc "1+1" "e*cos(pi)" "abs(-1)"'
      - run: 'printf "\n1+1\n6676767\ncos(pi)" > input && $(uname)_build/cmd/calc/calc < input && rm input'
      - run: 'scripts/win32_build.sh'
